# elcuk2 项目的依赖:
# 1. redis
# 2. elasticsearch
# 3. mysql
# PS:
# * 使用 docker-compose version 1
# * 如果不是 Linux 环境, 在 Mac OS 下是虚拟机中 IP, 不是 127.0.0.1
db:
  image: mysql:5.6
  container_name: hnglxcl-db
  environment:
    MYSQL_ROOT_PASSWORD: crater10lake
    MYSQL_DATABASE: hnglxcl
  ports:
   - "3306:3306"


